/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.semifinals.Activity1;

/**
 *
 * @author CL3
 */
import javax.swing.JOptionPane;
public class BankJFrame extends javax.swing.JFrame {

    /**
     * Creates new form BankJFrame
     */
    public BankJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LastName = new javax.swing.JTextField();
        FirstName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ExitButton = new javax.swing.JButton();
        AddInfo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        DisplayField = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        AccountInfo = new javax.swing.JTextField();
        BalanceInfo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        AmountSelection = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        WithdawButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        DepositButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        DepositField = new javax.swing.JTextField();
        ClearInfo = new javax.swing.JButton();
        ClearWithdaw = new javax.swing.JButton();
        ClearDeposit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastNameActionPerformed(evt);
            }
        });

        FirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstNameActionPerformed(evt);
            }
        });

        jLabel1.setText("Last Name:");

        jLabel2.setText("First Name:");

        ExitButton.setText("Exit");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        AddInfo.setText("Register");
        AddInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddInfoActionPerformed(evt);
            }
        });

        DisplayField.setColumns(20);
        DisplayField.setRows(5);
        jScrollPane1.setViewportView(DisplayField);

        jLabel3.setText("Account:");

        jLabel4.setText("Balance:");

        AccountInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccountInfoActionPerformed(evt);
            }
        });

        BalanceInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BalanceInfoActionPerformed(evt);
            }
        });

        jLabel5.setText("Withdraw");

        AmountSelection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"100" ,"200" ,"500" ,"1000" ,"3000" ,"5000" ,"6000" , "10000", "Other Amount"}));
        AmountSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AmountSelectionActionPerformed(evt);
            }
        });

        jLabel6.setText("Amount:");

        WithdawButton.setText("Withdraw");
        WithdawButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WithdawButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Cancel");

        jLabel7.setText("Welcome to Java Bank");

        jLabel8.setText("Deposit");

        jLabel9.setText("Amount:");

        DepositButton.setText("Deposit");
        DepositButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepositButtonActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");

        DepositField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepositFieldActionPerformed(evt);
            }
        });

        ClearInfo.setText("Clear");
        ClearInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearInfoActionPerformed(evt);
            }
        });

        ClearWithdaw.setText("Clear");
        ClearWithdaw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearWithdawActionPerformed(evt);
            }
        });

        ClearDeposit.setText("Clear");
        ClearDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearDepositActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(FirstName, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LastName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ClearInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AddInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(155, 155, 155))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(295, 295, 295))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(AmountSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(WithdawButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton1))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(DepositField)
                                                .addGap(18, 18, 18)
                                                .addComponent(DepositButton)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton2)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ClearWithdaw)
                            .addComponent(ClearDeposit)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AccountInfo)
                            .addComponent(BalanceInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel7)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LastName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClearInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AccountInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BalanceInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AmountSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(WithdawButton)
                    .addComponent(jButton1)
                    .addComponent(ClearWithdaw))
                .addGap(28, 28, 28)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(DepositButton)
                    .addComponent(jButton2)
                    .addComponent(DepositField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClearDeposit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    BankClass account = new BankClass();
    
    private void LastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastNameActionPerformed

    private void FirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstNameActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Thank You for Using Java Bank");
        System.exit(0);
        
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void AddInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddInfoActionPerformed
        // TODO add your handling code here:
        String info;

        account.setName(LastName.getText(), FirstName.getText());

        info = "Welcome " +account.getName()+ " to Java Bank";

        DisplayField.setText(info);
        AccountInfo.setText(account.getName());
        BalanceInfo.setText(account.getBalance()+"");
    }//GEN-LAST:event_AddInfoActionPerformed

    private void AccountInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccountInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AccountInfoActionPerformed

    private void BalanceInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BalanceInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BalanceInfoActionPerformed

    private void DepositFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepositFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DepositFieldActionPerformed

    private void ClearInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearInfoActionPerformed
        // TODO add your handling code here:
        FirstName.setText("");
        LastName.setText("");
    }//GEN-LAST:event_ClearInfoActionPerformed

    private void AmountSelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AmountSelectionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AmountSelectionActionPerformed

    private void WithdawButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WithdawButtonActionPerformed
        // TODO add your handling code here:
        String amountSelection[] = new String[]{"100" ,"200" ,"500" ,"1000" ,"3000" ,"5000" ,"6000" , "10000", "Other Amount"};

            if (AmountSelection.getSelectedItem() == amountSelection[0]){
                int amount = 100;
                if (amount > account.getBalance()){
                JOptionPane.showMessageDialog(null, "Cannot Withdraw with the Requested Amount", "Withdrawal", JOptionPane.WARNING_MESSAGE);

                } else {
                    account.withdraw(amount);
                    JOptionPane.showMessageDialog(null, "You Have Successfully Withdrawn " + amount+"$");
                }
            } else if (AmountSelection.getSelectedItem()  == amountSelection[1]){
                int amount = 200;
                if (amount > account.getBalance()){
                JOptionPane.showMessageDialog(null, "Cannot Withdraw with the Requested Amount", "Withdrawal", JOptionPane.WARNING_MESSAGE);

                } else {
                    account.withdraw(amount);
                    JOptionPane.showMessageDialog(null, "You Have Successfully Withdrawn " + amount+"$");
                }
            } else if (AmountSelection.getSelectedItem()  == amountSelection[2]){
                int amount = 500;
                if (amount > account.getBalance()){
                JOptionPane.showMessageDialog(null, "Cannot Withdraw with the Requested Amount", "Withdrawal", JOptionPane.WARNING_MESSAGE);

                } else {
                    account.withdraw(amount);
                    JOptionPane.showMessageDialog(null, "You Have Successfully Withdrawn " + amount+"$");
                }
            } else if (AmountSelection.getSelectedItem()  == amountSelection[3]){
                int amount = 1000;
                if (amount > account.getBalance()){
                JOptionPane.showMessageDialog(null, "Cannot Withdraw with the Requested Amount", "Withdrawal", JOptionPane.WARNING_MESSAGE);

                } else {
                    account.withdraw(amount);
                    JOptionPane.showMessageDialog(null, "You Have Successfully Withdrawn " + amount+"$");
                }
            } else if (AmountSelection.getSelectedItem()  == amountSelection[4]){
                int amount = 3000;
                if (amount > account.getBalance()){
                JOptionPane.showMessageDialog(null, "Cannot Withdraw with the Requested Amount", "Withdrawal", JOptionPane.WARNING_MESSAGE);

                } else {
                    account.withdraw(amount);
                    JOptionPane.showMessageDialog(null, "You Have Successfully Withdrawn " + amount+"$");
                }
            } else if (AmountSelection.getSelectedItem()  == amountSelection[5]){
                int amount = 5000;
                if (amount > account.getBalance()){
                JOptionPane.showMessageDialog(null, "Cannot Withdraw with the Requested Amount", "Withdrawal", JOptionPane.WARNING_MESSAGE);

                } else {
                    account.withdraw(amount);
                    JOptionPane.showMessageDialog(null, "You Have Successfully Withdrawn " + amount+"$");
                }
            } else if (AmountSelection.getSelectedItem()  == amountSelection[6]){
                int amount = 6000;
                if (amount > account.getBalance()){
                JOptionPane.showMessageDialog(null, "Cannot Withdraw with the Requested Amount", "Withdrawal", JOptionPane.WARNING_MESSAGE);

                } else {
                    account.withdraw(amount);
                    JOptionPane.showMessageDialog(null, "You Have Successfully Withdrawn " + amount+"$");
                }
            }else if (AmountSelection.getSelectedItem()  == amountSelection[7]){
                int amount = 10000;
                if (amount > account.getBalance()){
                JOptionPane.showMessageDialog(null, "Cannot Withdraw with the Requested Amount", "Withdrawal", JOptionPane.WARNING_MESSAGE);

                } else {
                    account.withdraw(amount);
                    JOptionPane.showMessageDialog(null, "You Have Successfully Withdrawn " + amount+"$");
                }
            


            }else if (AmountSelection.getSelectedItem()  == amountSelection[8]){
                String input = JOptionPane.showInputDialog(null,"Account Name: " + account.getName() +"\nBalance: "+ account.getBalance() +"\nEnter Amount to Withdraw:");
                        double amount = Double.parseDouble(input);
                        if (amount < 100 || amount > account.getBalance()){
                        JOptionPane.showMessageDialog(null, "Cannot Withdraw with the Requested Amount", "Withdrawal", JOptionPane.WARNING_MESSAGE);
                        
                        } else if (amount % 1 != 0 && amount % 2 != 0 && amount % 3 != 0 && amount % 5 != 0) {
                            JOptionPane.showMessageDialog(null, "Cannot Withdraw with the Requested Amount", "Withdrawal", JOptionPane.WARNING_MESSAGE);
                            
                        } else {
                            account.withdraw(amount);
                            JOptionPane.showMessageDialog(null, "You Have Successfully Withdrawn " + amount+"$");
                            
                        }
            }
        BalanceInfo.setText("");
        BalanceInfo.setText(account.getBalance()+"");    
        
    }//GEN-LAST:event_WithdawButtonActionPerformed

    private void DepositButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepositButtonActionPerformed
        // TODO add your handling code here:
        double depositMoney = Double.parseDouble(DepositField.getText());
        account.deposit(depositMoney);
        
        BalanceInfo.setText("");
        BalanceInfo.setText(account.getBalance()+"");
        JOptionPane.showMessageDialog(null, "You Have Successfully Deposited " + depositMoney +"$");
    }//GEN-LAST:event_DepositButtonActionPerformed

    private void ClearWithdawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearWithdawActionPerformed
        // TODO add your handling code here:
        AmountSelection.setSelectedIndex(0);
    }//GEN-LAST:event_ClearWithdawActionPerformed

    private void ClearDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearDepositActionPerformed
        // TODO add your handling code here:
        DepositField.setText("");
    }//GEN-LAST:event_ClearDepositActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BankJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BankJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BankJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BankJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BankJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AccountInfo;
    private javax.swing.JButton AddInfo;
    private javax.swing.JComboBox<String> AmountSelection;
    private javax.swing.JTextField BalanceInfo;
    private javax.swing.JButton ClearDeposit;
    private javax.swing.JButton ClearInfo;
    private javax.swing.JButton ClearWithdaw;
    private javax.swing.JButton DepositButton;
    private javax.swing.JTextField DepositField;
    private javax.swing.JTextArea DisplayField;
    private javax.swing.JButton ExitButton;
    private javax.swing.JTextField FirstName;
    private javax.swing.JTextField LastName;
    private javax.swing.JButton WithdawButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}